CREATE SCHEMA IF NOT EXISTS estudodecaso1_BD;

USE estudodecaso1_BD;

#1. EXEMPLOS DE 5 INSERTS POR TABELA

#INSERTS PARA FORNECEDORES
INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO, FORNEC_EMAIL)
VALUES (1, 'Fornecedor A', 'Rua A', '123', 'Bairro A', 'Cidade A', 'Estado A', 'Brasil', '12345-678', '1234567890', 'Contato A', 'fornecedorA@email.com');

INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO, FORNEC_EMAIL)
VALUES (2, 'Fornecedor B', 'Rua B', '456', 'Bairro B', 'Cidade B', 'Estado B', 'Brasil', '23456-789', '2345678901', 'Contato B', 'fornecedorB@email.com');

INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO, FORNEC_EMAIL)
VALUES (3, 'Fornecedor C', 'Rua C', '789', 'Bairro C', 'Cidade C', 'Estado C', 'Brasil', '34567-890', '3456789012', 'Contato C', 'fornecedorC@email.com');

INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO, FORNEC_EMAIL)
VALUES (4, 'Fornecedor D', 'Rua D', '101', 'Bairro D', 'Cidade D', 'Estado D', 'Brasil', '45678-901', '4567890123', 'Contato D', 'fornecedorD@email.com');

INSERT INTO FORNECEDORES (FORNEC_COD, FORNEC_NOME, FORNEC_RUA, FORNEC_NUMRUA, FORNEC_BAIRRO, FORNEC_CIDADE, FORNEC_ESTADO, FORNEC_PAIS, FORNEC_CODPOSTAL, FORNEC_TELEFONE, FORNEC_CONTATO, FORNEC_EMAIL)
VALUES (5, 'Fornecedor E', 'Rua E', '202', 'Bairro E', 'Cidade E', 'Estado E', 'Brasil', '56789-012', '5678901234', 'Contato E', 'fornecedorE@email.com');

#INSERTS PARA FILIAIS
INSERT INTO FILIAIS (FILIAIS_COD, FILIAIS_NOME, FILIAIS_RUA, FILIAIS_NUMRUA, FILIAIS_BAIRRO, FILIAIS_CIDADE, FILIAIS_ESTADO, FILIAIS_PAÍS, FILIAIS_CODPOSTAL, FILIAIS_CAPACIDADE)
VALUES (1, 'Filial A', 'Rua A', 123, 'Bairro A', 'Cidade A', 'Estado A', 'Brasil', '12345-678', 'Capacidade A');

INSERT INTO FILIAIS (FILIAIS_COD, FILIAIS_NOME, FILIAIS_RUA, FILIAIS_NUMRUA, FILIAIS_BAIRRO, FILIAIS_CIDADE, FILIAIS_ESTADO, FILIAIS_PAÍS, FILIAIS_CODPOSTAL, FILIAIS_CAPACIDADE)
VALUES (2, 'Filial B', 'Rua B', 456, 'Bairro B', 'Cidade B', 'Estado B', 'Brasil', '23456-789', 'Capacidade B');

INSERT INTO FILIAIS (FILIAIS_COD, FILIAIS_NOME, FILIAIS_RUA, FILIAIS_NUMRUA, FILIAIS_BAIRRO, FILIAIS_CIDADE, FILIAIS_ESTADO, FILIAIS_PAÍS, FILIAIS_CODPOSTAL, FILIAIS_CAPACIDADE)
VALUES (3, 'Filial C', 'Rua C', 789, 'Bairro C', 'Cidade C', 'Estado C', 'Brasil', '34567-890', 'Capacidade C');

INSERT INTO FILIAIS (FILIAIS_COD, FILIAIS_NOME, FILIAIS_RUA, FILIAIS_NUMRUA, FILIAIS_BAIRRO, FILIAIS_CIDADE, FILIAIS_ESTADO, FILIAIS_PAÍS, FILIAIS_CODPOSTAL, FILIAIS_CAPACIDADE)
VALUES (4, 'Filial D', 'Rua D', 101, 'Bairro D', 'Cidade D', 'Estado D', 'Brasil', '45678-901', 'Capacidade D');

INSERT INTO FILIAIS (FILIAIS_COD, FILIAIS_NOME, FILIAIS_RUA, FILIAIS_NUMRUA, FILIAIS_BAIRRO, FILIAIS_CIDADE, FILIAIS_ESTADO, FILIAIS_PAÍS, FILIAIS_CODPOSTAL, FILIAIS_CAPACIDADE)
VALUES (5, 'Filial E', 'Rua E', 202, 'Bairro E', 'Cidade E', 'Estado E', 'Brasil', '56789-012', 'Capacidade E');

#INSERTS PARA PRODUTOS 
INSERT INTO PRODUTOS (PRODUTOS_COD, PRODUTOS_NOME, PRODUTOS_DESCRIÇÃO, PRODUTOS_QUANT, PRODUTOS_PRECOUNIT, PRODUTOS_UNIMED, PRODUTOS_ESTOQMÍN)
VALUES (1, 'Produto A', 'Descrição do Produto A', 100.000, 50.00, 'un', 10.000);

INSERT INTO PRODUTOS (PRODUTOS_COD, PRODUTOS_NOME, PRODUTOS_DESCRIÇÃO, PRODUTOS_QUANT, PRODUTOS_PRECOUNIT, PRODUTOS_UNIMED, PRODUTOS_ESTOQMÍN)
VALUES (2, 'Produto B', 'Descrição do Produto B', 200.000, 30.00, 'kg', 20.000);

INSERT INTO PRODUTOS (PRODUTOS_COD, PRODUTOS_NOME, PRODUTOS_DESCRIÇÃO, PRODUTOS_QUANT, PRODUTOS_PRECOUNIT, PRODUTOS_UNIMED, PRODUTOS_ESTOQMÍN)
VALUES (3, 'Produto C', 'Descrição do Produto C', 150.000, 75.00, 'caixa', 15.000);

INSERT INTO PRODUTOS (PRODUTOS_COD, PRODUTOS_NOME, PRODUTOS_DESCRIÇÃO, PRODUTOS_QUANT, PRODUTOS_PRECOUNIT, PRODUTOS_UNIMED, PRODUTOS_ESTOQMÍN)
VALUES (4, 'Produto D', 'Descrição do Produto D', 300.000, 20.00, 'un', 30.000);

INSERT INTO PRODUTOS (PRODUTOS_COD, PRODUTOS_NOME, PRODUTOS_DESCRIÇÃO, PRODUTOS_QUANT, PRODUTOS_PRECOUNIT, PRODUTOS_UNIMED, PRODUTOS_ESTOQMÍN)
VALUES (5, 'Produto E', 'Descrição do Produto E', 250.000, 40.00, 'kg', 25.000);

#INSERTS PARA PEDIDOS
INSERT INTO PEDIDOS (PEDIDOS_COD, PEDIDOS_DATA, PEDIDOS_HORA, PEDIDOS_PREVISÃO, PEDIDOS_STATUS, PED_FORNECEDOR)
VALUES (1, '2024-11-10', '10:00:00', '2024-11-15', 'PENDENTE', 1);

INSERT INTO PEDIDOS (PEDIDOS_COD, PEDIDOS_DATA, PEDIDOS_HORA, PEDIDOS_PREVISÃO, PEDIDOS_STATUS, PED_FORNECEDOR)
VALUES (2, '2024-11-11', '11:00:00', '2024-11-16', 'CONCLUÍDO', 2);

INSERT INTO PEDIDOS (PEDIDOS_COD, PEDIDOS_DATA, PEDIDOS_HORA, PEDIDOS_PREVISÃO, PEDIDOS_STATUS, PED_FORNECEDOR)
VALUES (3, '2024-11-12', '12:00:00', '2024-11-17', 'EM ESPERA', 3);

INSERT INTO PEDIDOS (PEDIDOS_COD, PEDIDOS_DATA, PEDIDOS_HORA, PEDIDOS_PREVISÃO, PEDIDOS_STATUS, PED_FORNECEDOR)
VALUES (4, '2024-11-13', '14:00:00', '2024-11-18', 'PENDENTE', 4);

INSERT INTO PEDIDOS (PEDIDOS_COD, PEDIDOS_DATA, PEDIDOS_HORA, PEDIDOS_PREVISÃO, PEDIDOS_STATUS, PED_FORNECEDOR)
VALUES (5, '2024-11-14', '15:00:00', '2024-11-19', 'CONCLUÍDO', 5);

#INSERTS PARA RECEBIMENTOS
INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDIC, RECEB_PEDIDOS)
VALUES ('2024-11-10', '10:30:00', 50.000, 'Bom estado', 1);

INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDIC, RECEB_PEDIDOS)
VALUES ('2024-11-11', '11:15:00', 100.000, 'Bom estado', 2);

INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDIC, RECEB_PEDIDOS)
VALUES ('2024-11-12', '12:45:00', 75.000, 'Bom estado', 3);

INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDIC, RECEB_PEDIDOS)
VALUES ('2024-11-13', '14:30:00', 125.000, 'Bom estado', 4);

INSERT INTO RECEBIMENTOS (RECEB_DATA, RECEB_HORA, RECEB_QUANT_PROD, RECEB_CONDIC, RECEB_PEDIDOS)
VALUES ('2024-11-14', '15:45:00', 250.000, 'Bom estado', 5);

#INSERTS PARA PEDIDOS_PRODUTOS 
INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT, PRODUTOS_ESPECTEC)
VALUES (1, 1, 10.000, 'Em bom estado');

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT, PRODUTOS_ESPECTEC)
VALUES (2, 2, 20.000, 'Em bom estado');

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT, PRODUTOS_ESPECTEC)
VALUES (3, 3, 15.000, 'Em bom estado');

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT, PRODUTOS_ESPECTEC)
VALUES (4, 4, 30.000, 'Em bom estado');

INSERT INTO PEDIDOS_PRODUTOS (PDPR_PEDIDOS, PDPR_PRODUTOS, PDPR_QUANT, PRODUTOS_ESPECTEC)
VALUES (5, 5, 25.000, 'Em bom estado');

#INSERTS PARA FILIAIS_PRODUTOS 
INSERT INTO FILIAIS_PRODUTOS (FILPR_FILIAIS, FILPR_PROD, FLPR_QUANT)
VALUES (1, 1, 50.000);

INSERT INTO FILIAIS_PRODUTOS (FILPR_FILIAIS, FILPR_PROD, FLPR_QUANT)
VALUES (2, 2, 100.000);

INSERT INTO FILIAIS_PRODUTOS (FILPR_FILIAIS, FILPR_PROD, FLPR_QUANT)
VALUES (3, 3, 75.000);

INSERT INTO FILIAIS_PRODUTOS (FILPR_FILIAIS, FILPR_PROD, FLPR_QUANT)
VALUES (4, 4, 150.000);

INSERT INTO FILIAIS_PRODUTOS (FILPR_FILIAIS, FILPR_PROD, FLPR_QUANT)
VALUES (5, 5, 200.000);

#INSERTS PARA FORNEC_PRODUTOS
INSERT INTO FORNEC_PRODUTOS (FRPR_FORNEC, FRPR_PROD)
VALUES (1, 1);

INSERT INTO FORNEC_PRODUTOS (FRPR_FORNEC, FRPR_PROD)
VALUES (2, 2);

INSERT INTO FORNEC_PRODUTOS (FRPR_FORNEC, FRPR_PROD)
VALUES (3, 3);

INSERT INTO FORNEC_PRODUTOS (FRPR_FORNEC, FRPR_PROD)
VALUES (4, 4);

INSERT INTO FORNEC_PRODUTOS (FRPR_FORNEC, FRPR_PROD)
VALUES (5, 5);

#2. EXEMPLO DE 2 UPDATES POR TABELA 

#UPDATE PARA FORNECEDORES
UPDATE FORNECEDORES SET FORNEC_NOME = 'Fornecedor Atualizado' WHERE FORNEC_COD = 1;

UPDATE FORNECEDORES SET FORNEC_TELEFONE = '1234-5678' WHERE FORNEC_CODPOSTAL = '123456789' AND FORNEC_COD = 2;

#UPDATE PARA FILIAIS 
UPDATE FILIAIS SET FILIAIS_CAPACIDADE = '1000 m²' WHERE FILIAIS_COD = 1;

UPDATE FILIAIS SET FILIAIS_NOME = 'Filial Nova' WHERE FILIAIS_CIDADE = 'São Paulo' AND FILIAIS_COD = 2;

#UPDATE PARA PRODUTOS
UPDATE PRODUTOS SET PRODUTOS_PRECOUNIT = 49.99 WHERE PRODUTOS_COD = 1;

UPDATE PRODUTOS SET PRODUTOS_QUANT = 200.000 WHERE PRODUTOS_ESTOQMÍN > 50.000 AND PRODUTOS_COD = 2;

#UPDATE PARA PEDIDOS 
UPDATE PEDIDOS SET PEDIDOS_STATUS = 'CONCLUÍDO' WHERE PEDIDOS_COD = 1;

UPDATE PEDIDOS SET PEDIDOS_PREVISÃO = '2024-11-20' WHERE PEDIDOS_STATUS = 'PENDENTE' AND PEDIDOS_COD = 2;

#UPDATE PARA RECEBIMENTOS
UPDATE RECEBIMENTOS SET RECEB_QUANT_PROD = 100.000 WHERE RECEB_PEDIDOS = 1;

UPDATE RECEBIMENTOS SET RECEB_CONDIC = 'Em ótimo estado' WHERE RECEB_QUANT_PROD > 50.000 AND RECEB_PEDIDOS = 2;

#UPDATE PARA PEDIDOS_PRODUTOS
UPDATE PEDIDOS_PRODUTOS SET PDPR_QUANT = 15.000 WHERE PDPR_PEDIDOS = 1 AND PDPR_PRODUTOS = 1;

UPDATE PEDIDOS_PRODUTOS SET PRODUTOS_ESPECTEC = 'Excelente qualidade' WHERE PDPR_QUANT > 20.000 AND PDPR_PEDIDOS = 2;

#UPDATE PARA FILIAIS_PRODUTOS
UPDATE FILIAIS_PRODUTOS SET FLPR_QUANT = 60.000 WHERE FILPR_FILIAIS = 1 AND FILPR_PROD = 1;

UPDATE FILIAIS_PRODUTOS SET FLPR_QUANT = 120.000 WHERE FILPR_FILIAIS = 2 AND FILPR_PROD = 2;

#UPDATE PARA FORNEC_PRODUTOS
UPDATE FORNEC_PRODUTOS SET FRPR_FORNEC = 3 WHERE FRPR_FORNEC = 1 AND FRPR_PROD = 1;

UPDATE FORNEC_PRODUTOS SET FRPR_FORNEC = 2 WHERE FRPR_PROD = 2 AND FRPR_FORNEC = 3;

#3. EXEMPLO DE 1 DELETE POR TABELA

DELETE FROM PEDIDOS_PRODUTOS WHERE PDPR_PEDIDOS = 1;

DELETE FROM RECEBIMENTOS WHERE RECEB_PEDIDOS = 1;

DELETE FROM PEDIDOS WHERE PEDIDOS_COD = 1;

DELETE FROM FILIAIS_PRODUTOS WHERE FILPR_FILIAIS = 1;

DELETE FROM FORNEC_PRODUTOS WHERE FRPR_PROD = 1;

DELETE FROM FILIAIS WHERE FILIAIS_COD = 1;

DELETE FROM FORNECEDORES WHERE FORNEC_COD = 1;

DELETE FROM PRODUTOS WHERE PRODUTOS_COD = 1;
