CREATE DATABASE IF NOT EXISTS ProgramaFortificar;
USE ProgramaFortificar;

CREATE TABLE IF NOT EXISTS COLABORADOR (
    COLAB_ID INT PRIMARY KEY, 
    COLAB_NOME VARCHAR(100) NOT NULL, 
    COLAB_RUA VARCHAR(45) NOT NULL,
    COLAB_NUMRUA VARCHAR(45) NOT NULL,
    COLAB_BAIRRO VARCHAR(45) NOT NULL,
    COLAB_CIDADE VARCHAR(45) NOT NULL,
    COLAB_ESTADO VARCHAR(45) NOT NULL,
    COLAB_PAIS VARCHAR(30) NOT NULL,
    COLAB_CODPOSTAL VARCHAR(10) NOT NULL,
    COLAB_TELEFONE VARCHAR(15) NOT NULL,
    COLAB_EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTITUICAO (
    INST_ID INT PRIMARY KEY, 
    INST_NOME VARCHAR(100) NOT NULL, 
    INST_RUA VARCHAR(45) NOT NULL,
    INST_NUMRUA VARCHAR(45) NOT NULL,
    INST_BAIRRO VARCHAR(45) NOT NULL,
    INST_CIDADE VARCHAR(45) NOT NULL,
    INST_ESTADO VARCHAR(45) NOT NULL,
    INST_PAIS VARCHAR(30) NOT NULL,
    INST_CODPOSTAL VARCHAR(10) NOT NULL,
    INST_TELEFONE VARCHAR(15) NOT NULL,
    INST_EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS EDITAL (
    EDITAL_ID INT PRIMARY KEY,
    EDITAL_TITULO VARCHAR(100) NOT NULL,
    EDITAL_DATAPUB DATE NOT NULL,
    EDITAL_DATAFIM DATE NOT NULL,
    EDITAL_DESC TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJETO (
    PROJETO_ID INT PRIMARY KEY,
    PROJETO_NOME VARCHAR(100) NOT NULL,
    PROJETO_DESC VARCHAR(100) NOT NULL, 
    PROJETO_FOCO ENUM('SAUDE', 'EDUCACAO', 'ASSISTENCIA SOCIAL', 'MEIO AMBIENTE') NOT NULL, 
    PROJETO_INST INT NOT NULL, 
    PROJETO_EDIT INT NOT NULL,
    CONSTRAINT FK_INSTITUICAO FOREIGN KEY (PROJETO_INST) REFERENCES INSTITUICAO(INST_ID),
    CONSTRAINT FK_EDITAL FOREIGN KEY (PROJETO_EDIT) REFERENCES EDITAL(EDITAL_ID)
);

CREATE TABLE IF NOT EXISTS DOACAO (
    DOACAO_ID INT PRIMARY KEYDROP DATABASE IF EXISTS ProgramaFortificar;
CREATE DATABASE ProgramaFortificar;
USE ProgramaFortificar;

CREATE TABLE IF NOT EXISTS COLABORADOR (
    COLAB_ID INT PRIMARY KEY, 
    COLAB_NOME VARCHAR(100) NOT NULL, 
    COLAB_RUA VARCHAR(45) NOT NULL,
    COLAB_NUMRUA VARCHAR(45) NOT NULL,
    COLAB_BAIRRO VARCHAR(45) NOT NULL,
    COLAB_CIDADE VARCHAR(45) NOT NULL,
    COLAB_ESTADO VARCHAR(45) NOT NULL,
    COLAB_PAIS VARCHAR(30) NOT NULL,
    COLAB_CODPOSTAL VARCHAR(10) NOT NULL,
    COLAB_TELEFONE VARCHAR(15) NOT NULL,
    COLAB_EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTITUICAO (
    INST_ID INT PRIMARY KEY, 
    INST_NOME VARCHAR(100) NOT NULL, 
    INST_RUA VARCHAR(45) NOT NULL,
    INST_NUMRUA VARCHAR(45) NOT NULL,
    INST_BAIRRO VARCHAR(45) NOT NULL,
    INST_CIDADE VARCHAR(45) NOT NULL,
    INST_ESTADO VARCHAR(45) NOT NULL,
    INST_PAIS VARCHAR(30) NOT NULL,
    INST_CODPOSTAL VARCHAR(10) NOT NULL,
    INST_TELEFONE VARCHAR(15) NOT NULL,
    INST_EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS EDITAL (
    EDITAL_ID INT PRIMARY KEY,
    EDITAL_TITULO VARCHAR(100) NOT NULL,
    EDITAL_DATAPUB DATE NOT NULL,
    EDITAL_DATAFIM DATE NOT NULL,
    EDITAL_DESC TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJETO (
    PROJETO_ID INT PRIMARY KEY,
    PROJETO_NOME VARCHAR(100) NOT NULL,
    PROJETO_DESC VARCHAR(100) NOT NULL, 
    PROJETO_FOCO ENUM('SAUDE', 'EDUCACAO', 'ASSISTENCIA SOCIAL', 'MEIO AMBIENTE') NOT NULL, 
    PROJETO_INST INT NOT NULL, 
    PROJETO_EDIT INT NOT NULL,
    CONSTRAINT FK_INSTITUICAO FOREIGN KEY (PROJETO_INST) REFERENCES INSTITUICAO(INST_ID),
    CONSTRAINT FK_EDITAL FOREIGN KEY (PROJETO_EDIT) REFERENCES EDITAL(EDITAL_ID)
);

CREATE TABLE IF NOT EXISTS DOACAO (
    DOACAO_ID INT PRIMARY KEY,
    DOACAO_DATA DATE NOT NULL, 
    DOACAO_VALOR DECIMAL(10, 2) NOT NULL, 
    DOACAO_COLAB INT NOT NULL,
    DOACAO_PROJETO INT NOT NULL,
    CONSTRAINT FK_COLABORADOR FOREIGN KEY (DOACAO_COLAB) REFERENCES COLABORADOR(COLAB_ID),
    CONSTRAINT FK_PROJETO FOREIGN KEY (DOACAO_PROJETO) REFERENCES PROJETO(PROJETO_ID)
);

CREATE TABLE IF NOT EXISTS BENEFICIARIO (
    BENEF_ID INT PRIMARY KEY,
    BENEF_NOME VARCHAR(100) NOT NULL,
    BENEF_CPF VARCHAR(11) NOT NULL,
    BENEF_TIPOAJUDA VARCHAR(50),
    BENEF_PROJETO INT NOT NULL,
    CONSTRAINT FK_PROJETO_BENEF FOREIGN KEY (BENEF_PROJETO) REFERENCES PROJETO(PROJETO_ID)
);
