#0: EXEMPLO DE DROP POR SCHEMA
DROP SCHEMA estudodecaso1_BD;

#1: CRIAR O BANCO DE DADOS
create schema estudodecaso1_BD;

#2: USAR O BANCO DE DADOS
USE estudodecaso1_BD;

#3: CRIAR AS TABELAS NORMAIS
CREATE TABLE IF NOT EXISTS FORNECEDORES(
#Nome do atributo, tipo, restrição de integridade (ordem)
 
FORNEC_COD INT PRIMARY KEY, 
FORNEC_NOME VARCHAR(45) NOT NULL, 
FORNEC_RUA VARCHAR (45) NOT NULL,
FORNEC_NUMRUA VARCHAR (45) NOT NULL,
FORNEC_BAIRRO VARCHAR (45) NOT NULL,
FORNEC_CIDADE VARCHAR (45) NOT NULL,
FORNEC_ESTADO VARCHAR (45) NOT NULL,
FORNEC_PAIS VARCHAR (30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR (10) NOT NULL,
FORNEC_TELEFONE VARCHAR (15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FILIAIS (

FILIAIS_COD INT PRIMARY KEY,
FILIAIS_NOME VARCHAR (50) NOT NULL,
FILIAIS_RUA VARCHAR (100) NOT NULL,
FILIAIS_NUMRUA INT NOT NULL,
FILIAIS_BAIRRO VARCHAR (50) NOT NULL, 
FILIAIS_CIDADE VARCHAR (50) NOT NULL, 
FILIAIS_ESTADO VARCHAR (50) NOT NULL, 
FILIAIS_PAÍS VARCHAR (50) NOT NULL, 
FILIAIS_CODPOSTAL VARCHAR (10) NOT NULL, 
FILIAIS_CAPACIDADE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS ( 

PRODUTOS_COD INT PRIMARY KEY,
PRODUTOS_NOME VARCHAR (100) NOT NULL,
PRODUTOS_DESCRIÇÃO TEXT NOT NULL,
PRODUTOS_QUANT DECIMAL (10,3) NOT NULL,
PRODUTOS_PRECOUNIT DECIMAL (10,2) NOT NULL, 
PRODUTOS_UNIMED VARCHAR (10) NOT NULL,
PRODUTOS_ESTOQMÍN DECIMAL (10,3) NOT NULL
);

#4: CRIAR TABELAS COM AS FK's
CREATE TABLE IF NOT EXISTS PEDIDOS ( 

PEDIDOS_COD INT PRIMARY KEY,
PEDIDOS_DATA DATE NOT NULL,
PEDIDOS_HORA TIME NOT NULL,
PEDIDOS_PREVISÃO DATE NOT NULL, 
PEDIDOS_STATUS ENUM('PENDENTE', 'CONCLUÍDO', 'EM ESPERA'),
PED_FORNECEDOR INT NOT NULL,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA IDEIA
REFERENCES FORNECEDORES (FORNEC_COD)
);

CREATE TABLE IF NOT EXISTS RECEBIMENTOS (
#VEM DEPOIS PORQUE TEM DEPENDENCIA DE PEDIDOS
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDIC TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY (RECEB_PEDIDOS) REFERENCES PEDIDOS(PEDIDOS_COD)
);

#5: CRIAR AS ENTIDADES ASSOCIATIVAS

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS (
PDPR_PEDIDOS INT, 
PDPR_PRODUTOS INT, 
PRIMARY KEY(PDPR_PEDIDOS, PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,2) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS (PEDIDOS_COD),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY (PDPR_PRODUTOS) REFERENCES PRODUTOS (PRODUTOS_COD)
);

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS (
FILPR_FILIAIS INT,
FILPR_PROD INT, 
PRIMARY KEY (FILPR_FILIAIS, FILPR_PROD),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FILPR_FK_FILIAIS FOREIGN KEY (FILPR_FILIAIS) REFERENCES FILIAIS (FILIAIS_COD),
CONSTRAINT FILPR_FK_PROD FOREIGN KEY (FILPR_PROD) REFERENCES PRODUTOS (PRODUTOS_COD)
);

CREATE TABLE IF NOT EXISTS FORNEC_PRODUTOS (
FRPR_FORNEC INT, 
FRPR_PROD INT, 
PRIMARY KEY(FRPR_FORNEC, FRPR_PROD),
CONSTRAINT FRPR_FK_FORNEC FOREIGN KEY (FRPR_FORNEC) REFERENCES FORNECEDORES (FORNEC_COD),
CONSTRAINT FRPR_FK_PROD FOREIGN KEY (FRPR_PROD) REFERENCES PRODUTOS (PRODUTOS_COD)
);

#6: EXEMPLO DE ALTER TABLE
ALTER TABLE FORNECEDORES ADD FORNEC_EMAIL VARCHAR(100);
ALTER TABLE PRODUTOS ADD PRODUTOS_ESPECTEC TEXT NOT NULL;
ALTER TABLE RECEBIMENTOS RENAME COLUMN RECEB_CONDIC TO RECEB_CONDICAO;
ALTER TABLE PEDIDOS_PRODUTOS MODIFY PDPR_QUANT DECIMAL(10,3) NOT NULL;
ALTER TABLE FORNEC_PRODUTOS MODIFY FRPR_PROD INT NOT NULL;
CHANGE COLUMN FORNEC_TELEFONE FORNEC_TELEFONE VARCHAR(20) NOT NULL;
