DROP SCHEMA IF EXISTS estudodecaso4_BD;

# Criação do Banco de dados
CREATE SCHEMA IF NOT EXISTS estudodecaso4_BD;

# Uso do banco de dados
USE estudodecaso4_BD;

# Tabelas Normais
CREATE TABLE IF NOT EXISTS ALUNOS(
    ALUNO_ID INT PRIMARY KEY,
    ALUNO_NOME TEXT NOT NULL,
    ALUNO_CPF VARCHAR(11) NOT NULL,
    ALUNO_DATANASC DATE NOT NULL,
    ALUNO_CEP VARCHAR (8) NOT NULL,
    ALUNO_NUMRUA VARCHAR(5) NOT NULL,
    ALUNO_RUA VARCHAR (40) NOT NULL,
    ALUNO_BAIRRO VARCHAR (40) NOT NULL, 
    ALUNO_CIDADE VARCHAR (40) NOT NULL, 
    ALUNO_ESTADO VARCHAR (40) NOT NULL, 
    ALUNO_PAIS VARCHAR (40) NOT NULL,
    ALUNO_UF VARCHAR (2) NOT NULL,
    ALUNO_COMPLEMENTO TEXT
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
    INST_ID INT PRIMARY KEY,
    INST_NOME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS MODALIDADES (
    MOD_ID INT PRIMARY KEY,
    MOD_NOME TEXT
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    PAG_ID INT,
    PAG_DATA DATE NOT NULL,
    PAG_VALOR DECIMAL (5,2),
    PAG_STATUS TINYINT,
    ALUNOPAG_ID INT,
    PRIMARY KEY(PAG_ID, ALUNOPAG_ID),
    CONSTRAINT ALUNOID_FK FOREIGN KEY (ALUNOPAG_ID) REFERENCES ALUNOS (ALUNO_ID)
);

# Tabela intermediária para INSTRUTORES e MODALIDADES (muitos-para-muitos)
CREATE TABLE IF NOT EXISTS INST_MOD (
    INSTMOD_INST_ID INT,
    INSTMOD_MOD_ID INT,
    PRIMARY KEY (INSTMOD_INST_ID, INSTMOD_MOD_ID),
    CONSTRAINT INSTMOD_INST_FK FOREIGN KEY (INSTMOD_INST_ID) REFERENCES INSTRUTORES (INST_ID),
    CONSTRAINT INSTMOD_MOD_FK FOREIGN KEY (INSTMOD_MOD_ID) REFERENCES MODALIDADES (MOD_ID)
); 

CREATE TABLE IF NOT EXISTS AULAS (
    AULA_ID INT,
    AULA_CAPAC_ALUNOS INT NOT NULL,
    AULA_HORA TIME NOT NULL, 
    AULA_QNT_INSC INT NOT NULL,
    AULA_CAPAC INT NOT NULL,
    AULA_INST_ID INT,
    PRIMARY KEY (AULA_ID, AULA_INST_ID),
    CONSTRAINT AULAS_INSTID_FK FOREIGN KEY (AULA_INST_ID) REFERENCES INSTRUTORES (INST_ID)
);

CREATE TABLE IF NOT EXISTS ALUNO_AULA (
    ALUNOAULA_ALUNOID INT,
    ALUNOAULA_AULAID INT,
    PRIMARY KEY (ALUNOAULA_ALUNOID, ALUNOAULA_AULAID),
    CONSTRAINT ALUNOAULA_ALUNOID_FK FOREIGN KEY (ALUNOAULA_ALUNOID) REFERENCES ALUNOS (ALUNO_ID),
    CONSTRAINT ALUNOAULA_AULAID_FK FOREIGN KEY (ALUNOAULA_AULAID) REFERENCES AULAS (AULA_ID)
);

# Tabela PLANO_TREINAMENTO para associar ALUNOS com planos de treinamento específicos
CREATE TABLE IF NOT EXISTS PLANO_TREINAMENTO (
    PLANTREINO_ID INT, 
    PLANTREINO_DESC TEXT NOT NULL,
    PLANTREINO_DATACRIAÇÃO DATE NOT NULL,
    PLANTREINO_DATAATT DATE NOT NULL, 
    ALUNO_TREINO_ID INT,
    PT_INSTMOD_INST_ID INT, 
    PT_INSTMOD_MOD_ID INT,
    PRIMARY KEY (PLANTREINO_ID, ALUNO_TREINO_ID, PT_INSTMOD_INST_ID, PT_INSTMOD_MOD_ID),
    CONSTRAINT PLANO_ALUNOTREINOID_FK FOREIGN KEY (ALUNO_TREINO_ID) REFERENCES ALUNOS (ALUNO_ID),
    CONSTRAINT PLANO_INSTMOD_FK FOREIGN KEY (PT_INSTMOD_INST_ID, PT_INSTMOD_MOD_ID) REFERENCES INST_MOD (INSTMOD_INST_ID, INSTMOD_MOD_ID)
);

