#Exemplo de drop por table
DROP SCHEMA estudodecaso2_BD;

#Criação do Banco de dados
Create Schema estudodecaso2_BD;

#Banco de dados
Use estudodecaso2_BD;

#Tabelas Normais
Create table if not exists PASSAGEIROS(
PASS_CPF INT PRIMARY KEY, 
PASS_NOME VARCHAR (100) NOT NULL, 
PASS_TEL VARCHAR (10) NOT NULL,
PASS_EMAIL VARCHAR (100) NOT NULL, 
PASS_CEP VARCHAR (11) NOT NULL,
PASS_NUMRUA VARCHAR(5) NOT NULL,
PASS_RUA VARCHAR (40) NOT NULL,
PASS_BAIRRO VARCHAR (40) NOT NULL, 
PASS_CIDADE VARCHAR (40) NOT NULL, 
PASS_ESTADO VARCHAR (40) NOT NULL, 
PASS_PAIS VARCHAR (40) NOT NULL
);

Create table if not exists AEROPORTOS( 
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR (50) NOT NULL, 
AEROP_CIDADE VARCHAR (50) NOT NULL, 
AEROP_PAIS VARCHAR (30) NOT NULL,
AEROP_LATITUDE DECIMAL(9, 6) NOT NULL, 
AEROP_LONGITUDE DECIMAL(9, 6) NOT NULL
);

Create table if not exists AERONAVES (
AERON_PREFIXO INT PRIMARY KEY,
AERON_MODELO VARCHAR (50) NOT NULL,
AERON_ANOFABR YEAR NOT NULL,
AERON_FABRICANTE VARCHAR (50) NOT NULL,
AERON_CAPACIDADE DECIMAL (10, 2) NOT NULL,
AERON_AUTONOMIA VARCHAR(50) NOT NULL
);

Create table if not exists FUNCIONÁRIOS (
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR (50) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_CEP VARCHAR (11) NOT NULL,
FUNC_RUA VARCHAR (40) NOT NULL,
FUNC_BAIRRO VARCHAR (40) NOT NULL, 
FUNC_CIDADE VARCHAR (40) NOT NULL, 
FUNC_ESTADO VARCHAR (40) NOT NULL, 
FUNC_PAIS VARCHAR (40) NOT NULL,
FUNC_CPF VARCHAR (11) NOT NULL, 
FUN_FUNÇÃO TEXT NOT NULL
);
