CREATE SCHEMA estudodecaso3_BD;

USE estudodecaso3_BD;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLIENTE_ID INT PRIMARY KEY, 
CLIENTE_CNPJ VARCHAR(14) NOT NULL,
CLIENTE_RAZAOSOCIAL VARCHAR(50) NOT NULL,
CLI_RAMOATIVIDADE TEXT NOT NULL,
CLI_DATACAD DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPREGADOS (
EMP_MATRÍCULA INT PRIMARY KEY,
EMP_NOME VARCHAR(50) NOT NULL, 
EMP_DATAADMISSÃO DATE NOT NULL,
EMP_SALÁRIO DECIMAL (10,3) NOT NULL,
EMP_QUALIFICAÇÕES TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
FORNEC_ID INT PRIMARY KEY,
FORNEC_CNPJ VARCHAR (14) NOT NULL,
FORNEC_RAZÃOSOCIAL VARCHAR (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
PROD_ID INT PRIMARY KEY,
PROD_NOME VARCHAR (100) NOT NULL,
PROD_COR VARCHAR (20) NOT NULL,
PROD_DIMENSÕES DECIMAL (6,2) NOT NULL,
PROD_PESO DECIMAL (7,3) NOT NULL,
PROD_PREÇO DECIMAL (10,3) NOT NULL,
PROD_TEMPOFAB INT NOT NULL, 
PROD_DESENHO TEXT NOT NULL,
PROD_HORASMÃOOBRA TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTES (
TC_ID INT PRIMARY KEY,
TC_NOME VARCHAR (100) NOT NULL
);


CREATE TABLE IF NOT EXISTS MAQUINAS (
MAQ_ID INT PRIMARY KEY,
MAQ_TEMPOVIDA TIME NOT NULL,
MAQ_DATACOMPRA DATE NOT NULL,
MAQ_FIMGARANTIA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS (
RE_ID INT PRIMARY KEY,
RE_QNTNEC INT NOT NULL,
RE_UNIDADE INT NOT NULL,
RE_TEMPOUSO INT,
RE_HORASMÃOOBRA TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS CARGOS (
CARGO_ID INT PRIMARY KEY,
CARGO_FUNÇÃO TEXT NOT NULL,
CARGO_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS (
ENCO_NUM INT,
ENCO_DATAINCLUSÃO DATE NOT NULL,
ENCO_VALORTOTAL DECIMAL(10,3) NOT NULL,
ENCO_VALORDESCONTO DECIMAL(10,3) NOT NULL,
ENCO_VALORLÍQUIDO DECIMAL(10,3) NOT NULL,
ENCO_FORMAPAG TEXT NOT NULL,
ENCO_QNDPARCELAS INT NOT NULL,
ENCO_CLIENTEID INT,
PRIMARY KEY (ENCO_NUM, ENCO_CLIENTEID),
CONSTRAINT ENCO_CLIENTEID_FK FOREIGN KEY (ENCO_CLIENTEID) REFERENCES CLIENTES (CLIENTE_ID)
);

CREATE TABLE IF NOT EXISTS REGISTRO_MANUTENCAO (
RM_ID INT,
RM_DATA DATE NOT NULL,
RM_DESC TEXT NOT NULL,
RM_MAQID INT,
PRIMARY KEY (RM_ID, RM_MAQID),
CONSTRAINT RM_PROMAQ_FK FOREIGN KEY (RM_MAQID) REFERENCES MAQUINAS (MAQ_ID)
);

CREATE TABLE IF NOT EXISTS REGISTRO_SUPRIMENTO (
RS_ID INT, 
RS_QUANTIDADE INT NOT NULL,
RS_DATANECES DATE NOT NULL,
RM_PRODID INT,
PRIMARY KEY (RS_ID, RM_PRODID),
CONSTRAINT RS_PRODID_FK FOREIGN KEY (RM_PRODID) REFERENCES PRODUTOS (PROD_ID)
);

CREATE TABLE IF NOT EXISTS PESSOA_CONTATO (
PC_ID INT,
PC_FUNÇÃO TEXT NOT NULL,
PC_NOME VARCHAR(100) NOT NULL,
PC_CLIENTEID INT,
PRIMARY KEY (PC_ID, PC_CLIENTEID),
CONSTRAINT PC_CLIENTEID_FK FOREIGN KEY (PC_CLIENTEID) REFERENCES CLIENTES (CLIENTE_ID)
);

CREATE TABLE IF NOT EXISTS COMPONENTES (
COMP_ID INT,
COMP_NOME VARCHAR(100) NOT NULL,
COMP_PREÇOUNIT DECIMAL (10,3) NOT NULL,
COMP_UNIDADE INT NOT NULL, 
COMP_QNTESTOQUE INT NOT NULL,
COMP_PRODID INT,
PRIMARY KEY (COMP_ID, COMP_PRODID),
CONSTRAINT COMP_PRODID_FK FOREIGN KEY (COMP_PRODID) REFERENCES PRODUTOS (PROD_ID)
);


CREATE TABLE IF NOT EXISTS ENDEREÇOS (
END_ID INT, 
END_RUA VARCHAR(45) NOT NULL, 
END_NUMRUA VARCHAR(45) NOT NULL, 
END_LOGRADOURO VARCHAR(45) NOT NULL, 
END_ESTADO VARCHAR(45) NOT NULL, 
END_CIDADE VARCHAR(45) NOT NULL, 
END_BAIRRO VARCHAR(45) NOT NULL, 
END_CEP VARCHAR(11) NOT NULL, 
END_COMPLEMENTO VARCHAR(45) NOT NULL, 
END_CLIENTEID INT,
END_EMP_MATRÍCULA INT,
END_FORNECID INT, 
PRIMARY KEY (END_ID, END_CLIENTEID, END_EMP_MATRÍCULA, END_FORNECID),
CONSTRAINT END_CLIENTEID_FK FOREIGN KEY (END_CLIENTEID) REFERENCES CLIENTES (CLIENTE_ID),
CONSTRAINT END_EMP_MATRÍCULA_FK FOREIGN KEY (END_EMP_MATRÍCULA) REFERENCES EMPREGADOS (EMP_MATRÍCULA),
CONSTRAINT END_FORNECID_FK FOREIGN KEY (END_FORNECID) REFERENCES FORNECEDORES (FORNEC_ID)
);

CREATE TABLE IF NOT EXISTS TELEFONES (
TEL_ID INT,
TEL_NUM VARCHAR (11) NOT NULL,
TEL_CLIENTEID INT,
TEL_EMP_MATRÍCULA INT,
TEL_FORNECID INT, 
PRIMARY KEY (TEL_ID, TEL_CLIENTEID, TEL_EMP_MATRÍCULA, TEL_FORNECID),
CONSTRAINT TEL_CLIENTEID_FK FOREIGN KEY (TEL_CLIENTEID) REFERENCES CLIENTES (CLIENTE_ID),
CONSTRAINT TEL_EMP_MATRÍCULA_FK FOREIGN KEY (TEL_EMP_MATRÍCULA) REFERENCES EMPREGADOS (EMP_MATRÍCULA),
CONSTRAINT TEL_FORNECID_FK FOREIGN KEY (TEL_FORNECID) REFERENCES FORNECEDORES (FORNEC_ID)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS_PRODUTOS (
ENCPROD_ENCONUM INT,
ENCPROD_PRODID INT, 
PRIMARY KEY (ENCPROD_ENCONUM, ENCPROD_PRODID),
CONSTRAINT ENCPROD_ENCONUM_FK FOREIGN KEY (ENCPROD_ENCONUM) REFERENCES ENCOMENDAS (ENCO_NUM),
CONSTRAINT ENCPROD_PRODID_FK FOREIGN KEY (ENCPROD_PRODID) REFERENCES PRODUTOS (PROD_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_TC (
PRODTC_PRODID INT,
PRODTC_TCID INT, 
PRIMARY KEY (PRODTC_PRODID, PRODTC_TCID),
CONSTRAINT PRODTC_PRODID_FK FOREIGN KEY (PRODTC_PRODID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODTC_TCID_FK FOREIGN KEY (PRODTC_TCID) REFERENCES TIPO_COMPONENTES (TC_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_MAQ (
PRODMAQ_PRODID INT,
PRODMAQ_MAQID INT, 
PRIMARY KEY (PRODMAQ_PRODID, PRODMAQ_MAQID),
CONSTRAINT PRODMAQ_PRODID_FK FOREIGN KEY (PRODMAQ_PRODID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODMAQ_MAQID_FK FOREIGN KEY (PRODMAQ_MAQID) REFERENCES MAQUINAS (MAQ_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_RS (
PRODRS_PRODID INT,
PRODRS_RSID INT, 
PRIMARY KEY (PRODRS_PRODID, PRODRS_RSID),
CONSTRAINT PRODRS_PRODID_FK FOREIGN KEY (PRODRS_PRODID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODRS_RSID_FK FOREIGN KEY (PRODRS_RSID) REFERENCES REGISTRO_SUPRIMENTO (RS_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_RE (
PRODRE_PRODID INT,
PRODRE_REID INT, 
PRIMARY KEY (PRODRE_PRODID, PRODRE_REID),
CONSTRAINT PRODRE_REIDID_FK FOREIGN KEY (PRODRE_REID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODRE_REID_FK FOREIGN KEY (PRODRE_REID) REFERENCES RECURSOS_ESPECIFICOS (RE_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_EMPREGADOS (
PRODEMP_PRODID INT,
PRODEMP_REID INT, 
PRIMARY KEY (PRODEMP_PRODID, PRODEMP_REID),
CONSTRAINT PRODEMP_PRODID_FK FOREIGN KEY (PRODEMP_PRODID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODEMP_REID_FK FOREIGN KEY (PRODEMP_REID) REFERENCES EMPREGADOS (EMP_MATRÍCULA)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS_CARGO (
EMPCARGO_EMPID INT,
EMPCARGO_CARGOID INT, 
PRIMARY KEY (EMPCARGO_EMPID, EMPCARGO_CARGOID),
CONSTRAINT EMPCARGO_EMPID_FK FOREIGN KEY (EMPCARGO_EMPID) REFERENCES EMPREGADOS (EMP_MATRÍCULA),
CONSTRAINT EMPCARGO_CARGOID_FK FOREIGN KEY (EMPCARGO_CARGOID) REFERENCES CARGOS (CARGO_ID)
);

CREATE TABLE IF NOT EXISTS COMPONENTES_FORNECEDORES (
COMPFORNEC_COMPID INT,
COMPFORNEC_FORNECID INT, 
PRIMARY KEY (COMPFORNEC_COMPID, COMPFORNEC_FORNECID),
CONSTRAINT COMPFORNEC_COMPID_FK FOREIGN KEY (COMPFORNEC_COMPID) REFERENCES COMPONENTES (COMP_ID),
CONSTRAINT COMPFORNEC_FORNECID_FK FOREIGN KEY (COMPFORNEC_FORNECID) REFERENCES EMPREGADOS (EMP_MATRÍCULA)
);

#1. EXEMPLO DE ALTER TABLE: CLIENTES
ALTER TABLE CLIENTES ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE CLIENTES MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE CLIENTES CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE CLIENTES DROP COLUMN EXEMPLO_1234; 

#2. EXEMPLO DE ALTER TABLE: EMPREGADOS
ALTER TABLE EMPREGADOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE EMPREGADOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE EMPREGADOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE EMPREGADOS DROP COLUMN EXEMPLO_1234; 

#3. EXEMPLO DE ALTER TABLE: FORNECEDORES
ALTER TABLE FORNECEDORES ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE FORNECEDORES MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE FORNECEDORES CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE FORNECEDORES DROP COLUMN EXEMPLO_1234; 

#4. EXEMPLO DE ALTER TABLE: PRODUTOS
ALTER TABLE PRODUTOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PRODUTOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PRODUTOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PRODUTOS DROP COLUMN EXEMPLO_1234; 

#5. EXEMPLO DE ALTER TABLE: TIPO_COMPONENTES
ALTER TABLE TIPO_COMPONENTES ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE TIPO_COMPONENTES MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE TIPO_COMPONENTES CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE TIPO_COMPONENTES DROP COLUMN EXEMPLO_1234; 

#6. EXEMPLO DE ALTER TABLE: MAQUINAS
ALTER TABLE MAQUINAS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE MAQUINAS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE MAQUINAS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE MAQUINAS DROP COLUMN EXEMPLO_1234; 

#7. EXEMPLO DE ALTER TABLE: RECURSOS_ESPECIFICOS
ALTER TABLE RECURSOS_ESPECIFICOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE RECURSOS_ESPECIFICOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE RECURSOS_ESPECIFICOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE RECURSOS_ESPECIFICOS DROP COLUMN EXEMPLO_1234; 

#8. EXEMPLO DE ALTER TABLE: CARGOS
ALTER TABLE CARGOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE CARGOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE CARGOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE CARGOS DROP COLUMN EXEMPLO_1234; 

#9. EXEMPLO DE ALTER TABLE: ENCOMENDAS
ALTER TABLE ENCOMENDAS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE ENCOMENDAS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE ENCOMENDAS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE ENCOMENDAS DROP COLUMN EXEMPLO_1234; 

#10. EXEMPLO DE ALTER TABLE: REGISTRO_MANUTENCAO
ALTER TABLE REGISTRO_MANUTENCAO ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE REGISTRO_MANUTENCAO MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE REGISTRO_MANUTENCAO CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE REGISTRO_MANUTENCAO DROP COLUMN EXEMPLO_1234; 

#11. EXEMPLO DE ALTER TABLE: REGISTRO_SUPRIMENTO
ALTER TABLE REGISTRO_SUPRIMENTO ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE REGISTRO_SUPRIMENTO MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE REGISTRO_SUPRIMENTO CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE REGISTRO_SUPRIMENTO DROP COLUMN EXEMPLO_1234; 

#12. EXEMPLO DE ALTER TABLE: PESSOA_CONTATO
ALTER TABLE PESSOA_CONTATO ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PESSOA_CONTATO MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PESSOA_CONTATO CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PESSOA_CONTATO DROP COLUMN EXEMPLO_1234; 

#13. EXEMPLO DE ALTER TABLE: COMPONENTES
ALTER TABLE COMPONENTES ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE COMPONENTES MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE COMPONENTES CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE COMPONENTES DROP COLUMN EXEMPLO_1234; 

#14. EXEMPLO DE ALTER TABLE: ENDEREÇOS
ALTER TABLE ENDEREÇOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE ENDEREÇOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE ENDEREÇOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE ENDEREÇOS DROP COLUMN EXEMPLO_1234; 

#15. EXEMPLO DE ALTER TABLE: TELEFONES
ALTER TABLE TELEFONES ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE TELEFONES MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE TELEFONES CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE TELEFONES DROP COLUMN EXEMPLO_1234; 

#16. EXEMPLO DE ALTER TABLE: ENCOMENDAS_PRODUTOS
ALTER TABLE ENCOMENDAS_PRODUTOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE ENCOMENDAS_PRODUTOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE ENCOMENDAS_PRODUTOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE ENCOMENDAS_PRODUTOS DROP COLUMN EXEMPLO_1234; 

#17. EXEMPLO DE ALTER TABLE: PRODUTOS_TC
ALTER TABLE PRODUTOS_TC ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PRODUTOS_TC MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PRODUTOS_TC CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PRODUTOS_TC DROP COLUMN EXEMPLO_1234; 

#18. EXEMPLO DE ALTER TABLE: PRODUTOS_MAQ
ALTER TABLE PRODUTOS_MAQ ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PRODUTOS_MAQ MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PRODUTOS_MAQ CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PRODUTOS_MAQ DROP COLUMN EXEMPLO_1234; 

#19. EXEMPLO DE ALTER TABLE: PRODUTOS_RS
ALTER TABLE PRODUTOS_RS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PRODUTOS_RS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PRODUTOS_RS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PRODUTOS_RS DROP COLUMN EXEMPLO_1234; 

#20. EXEMPLO DE ALTER TABLE: PRODUTOS_RE
ALTER TABLE PRODUTOS_RE ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PRODUTOS_RE MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PRODUTOS_RE CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PRODUTOS_RE DROP COLUMN EXEMPLO_1234; 

#21. EXEMPLO DE ALTER TABLE: PRODUTOS_EMPREGADOS
ALTER TABLE PRODUTOS_EMPREGADOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PRODUTOS_EMPREGADOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PRODUTOS_EMPREGADOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PRODUTOS_EMPREGADOS DROP COLUMN EXEMPLO_1234; 

#22. EXEMPLO DE ALTER TABLE: EMPREGADOS_CARGO
ALTER TABLE EMPREGADOS_CARGO ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE EMPREGADOS_CARGO MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE EMPREGADOS_CARGO CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE EMPREGADOS_CARGO DROP COLUMN EXEMPLO_1234; 

#0: EXEMPLO DE DROP POR SCHEMA
DROP SCHEMA IF EXISTS estudodecaso3_BD;
