DROP SCHEMA IF EXISTS estudodecaso3_BD;

CREATE SCHEMA estudodecaso3_BD;

USE estudodecaso3_BD;

CREATE TABLE IF NOT EXISTS CLIENTES(
CLIENTE_ID INT PRIMARY KEY, 
CLIENTE_CNPJ VARCHAR(14) NOT NULL,
CLIENTE_RAZAOSOCIAL VARCHAR(50) NOT NULL,
CLI_RAMOATIVIDADE TEXT NOT NULL,
CLI_DATACAD DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPREGADOS (
EMP_MATRÍCULA INT PRIMARY KEY,
EMP_NOME VARCHAR(50) NOT NULL, 
EMP_DATAADMISSÃO DATE NOT NULL,
EMP_SALÁRIO DECIMAL (10,3) NOT NULL,
EMP_QUALIFICAÇÕES TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
FORNEC_ID INT PRIMARY KEY,
FORNEC_CNPJ VARCHAR (14) NOT NULL,
FORNEC_RAZÃOSOCIAL VARCHAR (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
PROD_ID INT PRIMARY KEY,
PROD_NOME VARCHAR (100) NOT NULL,
PROD_COR VARCHAR (20) NOT NULL,
PROD_DIMENSÕES DECIMAL (6,2) NOT NULL,
PROD_PESO DECIMAL (7,3) NOT NULL,
PROD_PREÇO DECIMAL (10,3) NOT NULL,
PROD_TEMPOFAB INT NOT NULL, 
PROD_DESENHO TEXT NOT NULL,
PROD_HORASMÃOOBRA TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTES (
TC_ID INT PRIMARY KEY,
TC_NOME VARCHAR (100) NOT NULL
);


CREATE TABLE IF NOT EXISTS MAQUINAS (
MAQ_ID INT PRIMARY KEY,
MAQ_TEMPOVIDA TIME NOT NULL,
MAQ_DATACOMPRA DATE NOT NULL,
MAQ_FIMGARANTIA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS RECURSOS_ESPECIFICOS (
RE_ID INT PRIMARY KEY,
RE_QNTNEC INT NOT NULL,
RE_UNIDADE INT NOT NULL,
RE_TEMPOUSO INT,
RE_HORASMÃOOBRA TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS CARGOS (
CARGO_ID INT PRIMARY KEY,
CARGO_FUNÇÃO TEXT NOT NULL,
CARGO_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS (
ENCO_NUM INT,
ENCO_DATAINCLUSÃO DATE NOT NULL,
ENCO_VALORTOTAL DECIMAL(10,3) NOT NULL,
ENCO_VALORDESCONTO DECIMAL(10,3) NOT NULL,
ENCO_VALORLÍQUIDO DECIMAL(10,3) NOT NULL,
ENCO_FORMAPAG TEXT NOT NULL,
ENCO_QNDPARCELAS INT NOT NULL,
ENCO_CLIENTEID INT,
PRIMARY KEY (ENCO_NUM, ENCO_CLIENTEID),
CONSTRAINT ENCO_CLIENTEID_FK FOREIGN KEY (ENCO_CLIENTEID) REFERENCES CLIENTES (CLIENTE_ID)
);

CREATE TABLE IF NOT EXISTS REGISTRO_MANUTENCAO (
RM_ID INT,
RM_DATA DATE NOT NULL,
RM_DESC TEXT NOT NULL,
RM_MAQID INT,
PRIMARY KEY (RM_ID, RM_MAQID),
CONSTRAINT RM_PROMAQ_FK FOREIGN KEY (RM_MAQID) REFERENCES MAQUINAS (MAQ_ID)
);

CREATE TABLE IF NOT EXISTS REGISTRO_SUPRIMENTO (
RS_ID INT, 
RS_QUANTIDADE INT NOT NULL,
RS_DATANECES DATE NOT NULL,
RM_PRODID INT,
PRIMARY KEY (RS_ID, RM_PRODID),
CONSTRAINT RS_PRODID_FK FOREIGN KEY (RM_PRODID) REFERENCES PRODUTOS (PROD_ID)
);

CREATE TABLE IF NOT EXISTS PESSOA_CONTATO (
PC_ID INT,
PC_FUNÇÃO TEXT NOT NULL,
PC_NOME VARCHAR(100) NOT NULL,
PC_CLIENTEID INT,
PRIMARY KEY (PC_ID, PC_CLIENTEID),
CONSTRAINT PC_CLIENTEID_FK FOREIGN KEY (PC_CLIENTEID) REFERENCES CLIENTES (CLIENTE_ID)
);

CREATE TABLE IF NOT EXISTS COMPONENTES (
COMP_ID INT,
COMP_NOME VARCHAR(100) NOT NULL,
COMP_PREÇOUNIT DECIMAL (10,3) NOT NULL,
COMP_UNIDADE INT NOT NULL, 
COMP_QNTESTOQUE INT NOT NULL,
COMP_PRODID INT,
PRIMARY KEY (COMP_ID, COMP_PRODID),
CONSTRAINT COMP_PRODID_FK FOREIGN KEY (COMP_PRODID) REFERENCES PRODUTOS (PROD_ID)
);


CREATE TABLE IF NOT EXISTS ENDEREÇOS (
END_ID INT, 
END_RUA VARCHAR(45) NOT NULL, 
END_NUMRUA VARCHAR(45) NOT NULL, 
END_LOGRADOURO VARCHAR(45) NOT NULL, 
END_ESTADO VARCHAR(45) NOT NULL, 
END_CIDADE VARCHAR(45) NOT NULL, 
END_BAIRRO VARCHAR(45) NOT NULL, 
END_CEP VARCHAR(11) NOT NULL, 
END_COMPLEMENTO VARCHAR(45) NOT NULL, 
END_CLIENTEID INT,
END_EMP_MATRÍCULA INT,
END_FORNECID INT, 
PRIMARY KEY (END_ID, END_CLIENTEID, END_EMP_MATRÍCULA, END_FORNECID),
CONSTRAINT END_CLIENTEID_FK FOREIGN KEY (END_CLIENTEID) REFERENCES CLIENTES (CLIENTE_ID),
CONSTRAINT END_EMP_MATRÍCULA_FK FOREIGN KEY (END_EMP_MATRÍCULA) REFERENCES EMPREGADOS (EMP_MATRÍCULA),
CONSTRAINT END_FORNECID_FK FOREIGN KEY (END_FORNECID) REFERENCES FORNECEDORES (FORNEC_ID)
);

CREATE TABLE IF NOT EXISTS TELEFONES (
TEL_ID INT,
TEL_NUM VARCHAR (11) NOT NULL,
TEL_CLIENTEID INT,
TEL_EMP_MATRÍCULA INT,
TEL_FORNECID INT, 
PRIMARY KEY (TEL_ID, TEL_CLIENTEID, TEL_EMP_MATRÍCULA, TEL_FORNECID),
CONSTRAINT TEL_CLIENTEID_FK FOREIGN KEY (TEL_CLIENTEID) REFERENCES CLIENTES (CLIENTE_ID),
CONSTRAINT TEL_EMP_MATRÍCULA_FK FOREIGN KEY (TEL_EMP_MATRÍCULA) REFERENCES EMPREGADOS (EMP_MATRÍCULA),
CONSTRAINT TEL_FORNECID_FK FOREIGN KEY (TEL_FORNECID) REFERENCES FORNECEDORES (FORNEC_ID)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS_PRODUTOS (
ENCPROD_ENCONUM INT,
ENCPROD_PRODID INT, 
PRIMARY KEY (ENCPROD_ENCONUM, ENCPROD_PRODID),
CONSTRAINT ENCPROD_ENCONUM_FK FOREIGN KEY (ENCPROD_ENCONUM) REFERENCES ENCOMENDAS (ENCO_NUM),
CONSTRAINT ENCPROD_PRODID_FK FOREIGN KEY (ENCPROD_PRODID) REFERENCES PRODUTOS (PROD_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_TC (
PRODTC_PRODID INT,
PRODTC_TCID INT, 
PRIMARY KEY (PRODTC_PRODID, PRODTC_TCID),
CONSTRAINT PRODTC_PRODID_FK FOREIGN KEY (PRODTC_PRODID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODTC_TCID_FK FOREIGN KEY (PRODTC_TCID) REFERENCES TIPO_COMPONENTES (TC_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_MAQ (
PRODMAQ_PRODID INT,
PRODMAQ_MAQID INT, 
PRIMARY KEY (PRODMAQ_PRODID, PRODMAQ_MAQID),
CONSTRAINT PRODMAQ_PRODID_FK FOREIGN KEY (PRODMAQ_PRODID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODMAQ_MAQID_FK FOREIGN KEY (PRODMAQ_MAQID) REFERENCES MAQUINAS (MAQ_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_RS (
PRODRS_PRODID INT,
PRODRS_RSID INT, 
PRIMARY KEY (PRODRS_PRODID, PRODRS_RSID),
CONSTRAINT PRODRS_PRODID_FK FOREIGN KEY (PRODRS_PRODID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODRS_RSID_FK FOREIGN KEY (PRODRS_RSID) REFERENCES REGISTRO_SUPRIMENTO (RS_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_RE (
PRODRE_PRODID INT,
PRODRE_REID INT, 
PRIMARY KEY (PRODRE_PRODID, PRODRE_REID),
CONSTRAINT PRODRE_REIDID_FK FOREIGN KEY (PRODRE_REID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODRE_REID_FK FOREIGN KEY (PRODRE_REID) REFERENCES RECURSOS_ESPECIFICOS (RE_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_EMPREGADOS (
PRODEMP_PRODID INT,
PRODEMP_REID INT, 
PRIMARY KEY (PRODEMP_PRODID, PRODEMP_REID),
CONSTRAINT PRODEMP_PRODID_FK FOREIGN KEY (PRODEMP_PRODID) REFERENCES PRODUTOS (PROD_ID),
CONSTRAINT PRODEMP_REID_FK FOREIGN KEY (PRODEMP_REID) REFERENCES EMPREGADOS (EMP_MATRÍCULA)
);

CREATE TABLE IF NOT EXISTS EMPREGADOS_CARGO (
EMPCARGO_EMPID INT,
EMPCARGO_CARGOID INT, 
PRIMARY KEY (EMPCARGO_EMPID, EMPCARGO_CARGOID),
CONSTRAINT EMPCARGO_EMPID_FK FOREIGN KEY (EMPCARGO_EMPID) REFERENCES EMPREGADOS (EMP_MATRÍCULA),
CONSTRAINT EMPCARGO_CARGOID_FK FOREIGN KEY (EMPCARGO_CARGOID) REFERENCES CARGOS (CARGO_ID)
);

CREATE TABLE IF NOT EXISTS COMPONENTES_FORNECEDORES (
COMPFORNEC_COMPID INT,
COMPFORNEC_FORNECID INT, 
PRIMARY KEY (COMPFORNEC_COMPID, COMPFORNEC_FORNECID),
CONSTRAINT COMPFORNEC_COMPID_FK FOREIGN KEY (COMPFORNEC_COMPID) REFERENCES COMPONENTES (COMP_ID),
CONSTRAINT COMPFORNEC_FORNECID_FK FOREIGN KEY (COMPFORNEC_FORNECID) REFERENCES EMPREGADOS (EMP_MATRÍCULA)
);
