#Criação do Banco de dados
Create Schema estudodecaso2_BD;

#Uso do Banco de dados
Use Schema estudodecaso2_BD;

#Criar Tabelas Normais
Create table if not exists PASSAGEIROS(
PASS_CPF INT PRIMARY KEY, 
PASS_NOME VARCHAR (100) NOT NULL, 
PASS_TEL VARCHAR (10) NOT NULL,
PASS_EMAIL VARCHAR (100) NOT NULL, 
PASS_CEP VARCHAR (11) NOT NULL,
PASS_NUMRUA VARCHAR(5) NOT NULL,
PASS_RUA VARCHAR (40) NOT NULL,
PASS_BAIRRO VARCHAR (40) NOT NULL, 
PASS_CIDADE VARCHAR (40) NOT NULL, 
PASS_ESTADO VARCHAR (40) NOT NULL, 
PASS_PAIS VARCHAR (40) NOT NULL
);

Create table if not exists VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL, 
);