CREATE SCHEMA estudodecaso1_BD;

USE estudodecaso1_BD;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
 
FORNEC_COD INT PRIMARY KEY, 
FORNEC_NOME VARCHAR(45) NOT NULL, 
FORNEC_RUA VARCHAR (45) NOT NULL,
FORNEC_NUMRUA VARCHAR (45) NOT NULL,
FORNEC_BAIRRO VARCHAR (45) NOT NULL,
FORNEC_CIDADE VARCHAR (45) NOT NULL,
FORNEC_ESTADO VARCHAR (45) NOT NULL,
FORNEC_PAIS VARCHAR (30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR (10) NOT NULL,
FORNEC_TELEFONE VARCHAR (15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL,
FORNEC_EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILIAIS (

FILIAIS_COD INT PRIMARY KEY,
FILIAIS_NOME VARCHAR (50) NOT NULL,
FILIAIS_RUA VARCHAR (100) NOT NULL,
FILIAIS_NUMRUA INT NOT NULL,
FILIAIS_BAIRRO VARCHAR (50) NOT NULL, 
FILIAIS_CIDADE VARCHAR (50) NOT NULL, 
FILIAIS_ESTADO VARCHAR (50) NOT NULL, 
FILIAIS_PAÍS VARCHAR (50) NOT NULL, 
FILIAIS_CODPOSTAL VARCHAR (10) NOT NULL, 
FILIAIS_CAPACIDADE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS ( 

PRODUTOS_COD INT PRIMARY KEY,
PRODUTOS_NOME VARCHAR (100) NOT NULL,
PRODUTOS_DESCRIÇÃO TEXT NOT NULL,
PRODUTOS_QUANT DECIMAL (10,3) NOT NULL,
PRODUTOS_PRECOUNIT DECIMAL (10,2) NOT NULL, 
PRODUTOS_UNIMED VARCHAR (10) NOT NULL,
PRODUTOS_ESTOQMÍN DECIMAL (10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDOS ( 

PEDIDOS_COD INT PRIMARY KEY,
PEDIDOS_DATA DATE NOT NULL,
PEDIDOS_HORA TIME NOT NULL,
PEDIDOS_PREVISÃO DATE NOT NULL, 
PEDIDOS_STATUS ENUM('PENDENTE', 'CONCLUÍDO', 'EM ESPERA'),
PED_FORNECEDOR INT NOT NULL,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA IDEIA
REFERENCES FORNECEDORES (FORNEC_COD)
);

CREATE TABLE IF NOT EXISTS RECEBIMENTOS (
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDIC TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY (RECEB_PEDIDOS) REFERENCES PEDIDOS(PEDIDOS_COD)
);

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS (
PDPR_PEDIDOS INT, 
PDPR_PRODUTOS INT, 
PRIMARY KEY(PDPR_PEDIDOS, PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,2) NOT NULL,
PRODUTOS_ESPECTEC TEXT NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS (PEDIDOS_COD),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY (PDPR_PRODUTOS) REFERENCES PRODUTOS (PRODUTOS_COD)
);

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS (
FILPR_FILIAIS INT,
FILPR_PROD INT, 
PRIMARY KEY (FILPR_FILIAIS, FILPR_PROD),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FILPR_FK_FILIAIS FOREIGN KEY (FILPR_FILIAIS) REFERENCES FILIAIS (FILIAIS_COD),
CONSTRAINT FILPR_FK_PROD FOREIGN KEY (FILPR_PROD) REFERENCES PRODUTOS (PRODUTOS_COD)
);

CREATE TABLE IF NOT EXISTS FORNEC_PRODUTOS (
FRPR_FORNEC INT, 
FRPR_PROD INT, 
PRIMARY KEY(FRPR_FORNEC, FRPR_PROD),
CONSTRAINT FRPR_FK_FORNEC FOREIGN KEY (FRPR_FORNEC) REFERENCES FORNECEDORES (FORNEC_COD),
CONSTRAINT FRPR_FK_PROD FOREIGN KEY (FRPR_PROD) REFERENCES PRODUTOS (PRODUTOS_COD)
);

#1: EXEMPLO DE ALTER TABLE: FORNECEDORES (Add, Drop, Modify e Change)
ALTER TABLE FORNECEDORES ADD EXEMPLO_123 TEXT;
ALTER TABLE FORNECEDORES MODIFY EXEMPLO_123 DECIMAL(10,3);
ALTER TABLE FORNECEDORES CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL;
ALTER TABLE FORNECEDORES DROP COLUMN EXEMPLO_1234;

#2: EXEMPLO DE ALTER TABLE: FILIAIS
ALTER TABLE FILIAIS ADD EXEMPLO_123 TEXT;
ALTER TABLE FILIAIS MODIFY EXEMPLO_123 DECIMAL(10,3);
ALTER TABLE FILIAIS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL;
ALTER TABLE FILIAIS DROP COLUMN EXEMPLO_1234;

#3: EXEMPLO DE ALTER TABLE: PEDIDOS
ALTER TABLE PEDIDOS ADD EXEMPLO_123 TEXT;
ALTER TABLE PEDIDOS MODIFY EXEMPLO_123 DECIMAL(10,3);
ALTER TABLE PEDIDOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL;
ALTER TABLE PEDIDOS DROP COLUMN EXEMPLO_1234;

#4. EXEMPLO DE ALTER TABLE: PRODUTOS
ALTER TABLE PRODUTOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PRODUTOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PRODUTOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PRODUTOS DROP COLUMN EXEMPLO_1234;

#5. EXEMPLO DE ALTER TABLE: RECEBIMENTOS
ALTER TABLE RECEBIMENTOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE RECEBIMENTOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE RECEBIMENTOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE RECEBIMENTOS DROP COLUMN EXEMPLO_1234;

#6. EXEMPLO DE ALTER TABLE: PEDIDOS_PRODUTOS
ALTER TABLE PEDIDOS_PRODUTOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE PEDIDOS_PRODUTOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE PEDIDOS_PRODUTOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN EXEMPLO_1234;

#7. EXEMPLO DE ALTER TABLE: FILIAIS_PRODUTOS
ALTER TABLE FILIAIS_PRODUTOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE FILIAIS_PRODUTOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE FILIAIS_PRODUTOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN EXEMPLO_1234;

#8. EXEMPLO DE ALTER TABLE: FORNEC_PRODUTOS
ALTER TABLE FORNEC_PRODUTOS ADD EXEMPLO_123 TEXT NOT NULL; 
ALTER TABLE FORNEC_PRODUTOS MODIFY EXEMPLO_123 DECIMAL(10,3); 
ALTER TABLE FORNEC_PRODUTOS CHANGE COLUMN EXEMPLO_123 EXEMPLO_1234 VARCHAR(20) NOT NULL; 
ALTER TABLE FORNEC_PRODUTOS DROP COLUMN EXEMPLO_1234;

#0: EXEMPLO DE DROP POR SCHEMA
DROP SCHEMA estudodecaso1_BD;
