DROP SCHEMA IF EXISTS estudodecaso5_BD;

CREATE SCHEMA estudodecaso5_BD;

USE estudodecaso5_BD;

CREATE TABLE IF NOT EXISTS CLIENTES (
    CLIENTE_CPF VARCHAR(14) PRIMARY KEY,
    CLIENTE_NOME VARCHAR(50) NOT NULL,
    CLIENTE_DATANASC DATE NOT NULL,
    CLIENTE_STATUSFID ENUM('ATIVO', 'INATIVO') NOT NULL,
    CLIENTE_RUA VARCHAR(45) NOT NULL,
    CLIENTE_NUMRUA INT NOT NULL,
    CLIENTE_BAIRRO VARCHAR(45) NOT NULL,
    CLIENTE_REFERENCIA TEXT NOT NULL,
    CLIENTE_CIDADE VARCHAR(45) NOT NULL,
    CLIENTE_ESTADO VARCHAR(45) NOT NULL, 
    CLIENTE_CEP VARCHAR(11) NOT NULL, 
    CLIENTE_PAIS VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    PROD_ID INT PRIMARY KEY,
    PROD_NOME VARCHAR(45) NOT NULL, 
    PROD_QUANT INT NOT NULL,
    PROD_PRECO DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
    FORNEC_ID INT PRIMARY KEY,
    FORNEC_NOME VARCHAR(45) NOT NULL, 
    FORNEC_CONTATO TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDAS (
    VENDA_ID INT PRIMARY KEY,
    VENDA_CLIENTE_CPF VARCHAR(14),
    CONSTRAINT VENDA_CLIENTEID_FK FOREIGN KEY (VENDA_CLIENTE_CPF) REFERENCES CLIENTES (CLIENTE_CPF)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    PAG_ID INT,
    PAG_DATA DATE NOT NULL,
    PAG_VALOR DECIMAL(10,2) NOT NULL,
    PAG_STATUS ENUM('PAGO', 'NAO PAGO'),
    PAG_VENDAID INT,
    PRIMARY KEY (PAG_ID, PAG_VENDAID),
    CONSTRAINT PAG_VENDAID_FK FOREIGN KEY (PAG_VENDAID) REFERENCES VENDAS (VENDA_ID)
);

CREATE TABLE IF NOT EXISTS VENDAS_PRODUTOS (
    VENDPROD_VENDAID INT,
    VENDPROD_PRODID INT,
    VEND_PROD_QNTVENDIDA INT NOT NULL,
    VEND_PROD_VALORVENDA DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (VENDPROD_VENDAID, VENDPROD_PRODID),
    CONSTRAINT VENDPROD_VENDAID_FK FOREIGN KEY (VENDPROD_VENDAID) REFERENCES VENDAS (VENDA_ID),
    CONSTRAINT VENDPROD_PRODID_FK FOREIGN KEY (VENDPROD_PRODID) REFERENCES PRODUTOS (PROD_ID)
);

CREATE TABLE IF NOT EXISTS PROD_FORNEC (
    PRODFORNEC_PRODID INT,
    PRODFORNEC_FORNECID INT,
    PRIMARY KEY (PRODFORNEC_PRODID, PRODFORNEC_FORNECID), 
    CONSTRAINT PRODFORNEC_PRODID_FK FOREIGN KEY (PRODFORNEC_PRODID) REFERENCES PRODUTOS (PROD_ID),
    CONSTRAINT PRODFORNEC_FORNECID_FK FOREIGN KEY (PRODFORNEC_FORNECID) REFERENCES FORNECEDORES (FORNEC_ID)
);